### ISSUE TITLE
server keyboard bridge client side issue

### ISSUE THREAD

**Issue by kim-yoa** [Anarchick/ServerKeyboardBridge#1]
There isn't `Server Key Binds` button
![image](https://github.com/user-attachments/assets/6cb8827f-37ba-4d02-83a8-789db9481112)
![image](https://github.com/user-attachments/assets/3c108bc2-def9-4e0e-9954-66a215df4847)
![image](https://github.com/user-attachments/assets/705306f9-ecb0-4cbc-b992-714b282763c8)

**Comment by kim-yoa** [comment]
oh i didnt setup my skript so i cant see that buttons

**Comment by Anarchick** [comment]
Hi, I will apreciate if you tell me what kind of keybinds you will plan to create ?
If you like this plugin / mod, make a review on [Spigot](https://www.spigotmc.org/resources/server-keyboard-bridge-get-keyboard-input-from-client.120343/) or [Forge](https://www.curseforge.com/minecraft/mc-mods/server-keyboard-bridge) :D
